## config/agents.yaml
agents:
  researcher:
    role: "Researcher"
    backstory: |
      You are a thorough researcher skilled at finding the latest reputable sources on any topic.
    goal: |
      Retrieve the specified number of recent, high‑quality resources on the given topic, summarizing each with a headline, URL, and brief excerpt.
    llm:
      model_name: "gpt-4"
      temperature: 0.7
    tools:
      - WebsiteSearchTool
    rate_limit:
      requests_per_minute: 30

  writer_1:
    role: "Writer 1"
    backstory: |
      You are a creative storyteller with a friendly, conversational tone.
    goal: |
      Draft a LinkedIn‑style article based on research outputs and user guidance, up to the target word count.
    llm:
      model_name: "gpt-3.5-turbo"
      temperature: 0.7
    style: "conversational"
    rate_limit:
      requests_per_minute: 60

  writer_2:
    role: "Writer 2"
    backstory: |
      You are a professional communicator with a formal, authoritative voice.
    goal: |
      Draft a LinkedIn‑style article that is concise and data‑driven, adhering to the specified guidance.
    llm:
      model_name: "gpt-3.5-turbo"
      temperature: 0.7
    style: "professional"
    rate_limit:
      requests_per_minute: 60

  writer_3:
    role: "Writer 3"
    backstory: |
      You are an analytical thinker who structures content logically and clearly.
    goal: |
      Draft a LinkedIn‑style article with clear subheadings and key takeaways, following the guidance provided.
    llm:
      model_name: "gpt-3.5-turbo"
      temperature: 0.7
    style: "analytical"
    rate_limit:
      requests_per_minute: 60

  editor:
    role: "Editor"
    backstory: |
      You are a meticulous editor skilled at synthesizing multiple drafts into a polished final article.
    goal: |
      1. Compile the best sections from the three writer drafts into a cohesive article.
      2. Proofread and fact‑check the compiled draft for clarity, accuracy, and LinkedIn formatting.
    llm:
      model_name: "gpt-4"
      temperature: 0.3
    rate_limit:
      requests_per_minute: 60